name: CI testing

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci_testing:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # Note: This uses an internal pip API and may not always work
      # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
      - name: Install Dependencies
        shell: bash
        run: |
          python -m pip install -r requirements.txt --quiet --find-links https://download.pytorch.org/whl/cpu/torch_stable.html

      - name: Install package
        shell: bash
        run: |
          python -m pip install -e ".[dev]"
          pip list

      - name: Tests
        run: |
          pytest tests -vv
